baseURL       = "/"
languageCode  = "en-us"
title         = "ElectricienCoteDazur"
theme         = "roxo"
summarylength = 25
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "ElectricienCoteDazur"
weight = 1
languageName = "English"

  [[Languages.en.menu.main]]
     url     = "/portfolio"
     name    = "Services"
     weight  = 1
    
  [[Languages.en.menu.main]]
    url     = "/tarifs"
    name    = "Prices"
    weight  = 4
  [[Languages.en.menu.main]]
    url     = "/about"
    name    = "About"
    weight  = 5
  [[Languages.en.menu.main]]
    url     = "/contact"
    name    = "Contact"
    weight  = 6

  # Banner Section
    [Languages.en.params.banner]
    enable                = true
    background_image      = "images/backgrounds/ghenadie-ciobanu-electricien-cote-dazur2.jpg"
    heading               = "If you have a problem that requires the intervention of an electrician, you know who to call 07 53 81 78 02 "
    tagline               = "My name is Ghenadie Ciobanu and I can't do everything! When I have a problem with my car, I go to the mechanic. If I feel bad, I go to the doctor. Each of us has experience in one or more fields, but we certainly cannot do them all. When it comes to electricity, this is the field in which I am an expert."
    primary_button        = "Prices"
    primary_button_url    = "/en/blog"
    secondary_button      = "Services"
    secondary_button_url  = "portfolio"
  
  [Languages.en.params.blog]
    enable    = true
    title     = "Articles:"
    subtitle  = "Seeking to make the complex clear & practical." 
    more      = "VIEW MORE ARTICLES"
    viewarticle = "View Article" 
    
  [Languages.en.params.portfolio]
    enable    = true
    title     = "Services:"
    subtitle  = "I will definitely find the optimal solution for you."
    more      = "VIEW MORE SERVICES"
    amazonbutton = "Prices"
    viewbook = "View Service"
    

  

  [Languages.en.params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Prices"
    primary_button_url  = "/en/blog"
    secondary_button    = "Services"
    secondary_button_url = "/en/portfolio"



    
    
[Languages.fr]
title = "Electricien Cote D'azur"
weight = 2
languageName = "Français"

  [[Languages.fr.menu.main]]
    url     = "/fr/portfolio"
    name    = "Services"
    weight  = 1
    
  [[Languages.fr.menu.main]]
    url     = "/fr/tarifs"
    name    = "Tarifs"
    weight  = 4  
  [[Languages.fr.menu.main]]
    url     = "/fr/about"
    name    = "À propos"
    weight  = 5
  [[Languages.fr.menu.main]]
    url     = "/contact"
    name    = "Contact"
    weight  = 6
  # Banner Section
    [Languages.fr.params.banner]
    enable                = true
    background_image      = "images/backgrounds/ghenadie-ciobanu-electricien-cote-dazur2.jpg"
    heading               = "Si vous avez un problème qui nécessite l'intervention d'un électricien, vous savez qui appeler 07 53 81 78 02 "
    tagline               = "Je m'appelle Ghenadie Ciobanu et je ne peux pas tout faire ! Quand j'ai un problème avec ma voiture, je vais chez le mécanicien. Si je me sens mal, je vais chez le médecin. Chacun de nous a de l'expérience dans un ou plusieurs domaines, mais nous ne pouvons certainement pas tous les faire.En matière d'électricité, c'est le domaine dans lequel je suis un expert."
    primary_button        = "Tarifs"
    primary_button_url    = "/fr/blog"
    secondary_button      = "Services"
    secondary_button_url  = "portfolio"

  [Languages.fr.params.blog]
    enable    = true
    title     = "Services:"
    subtitle  = "Complexitatea devine clară și practică."
    more      = "VEZI MAI MULTE ARTICOLE" 
    viewarticle = "Vezi Articolul"  

  [Languages.fr.params.portfolio]
    enable    = true
    title     = "Services:"
    subtitle  = "Je trouverai certainement la solution optimale pour vous."
    more      = "VOIR PLUS DE SERVICES"
    amazonbutton = "Tarifs"
    viewbook = "Voir le service"

[Languages.fr.params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Travaillons ensemble"
    primary_button      = "Tarifs"
    primary_button_url  = "/fr/blog"
    secondary_button    = "Services"
    secondary_button_url = "/fr/portfolio"
    

    
  
# # Site Menus
# [menu]
#   # Navbar Menus
#   [[menu.nav]]
#     name    = "Home"
#     url     = ""
#     weight  = 1
#   [[menu.nav]]
#     name    = "Despre"
#     url     = "about"
#     weight  = 2
#     [[menu.nav]]
#     name    = "FAQ"
#     url     = "portfolio"
#     weight  = 3
#   [[menu.nav]]
#     name    = "Blog"
#     url     = "blog"
#     weight  = 4
#   [[menu.nav]]
#     name    = "Contacte"
#     url     = "contact"
#     weight  = 5

# Site Params
[params]
  logo = "images/electricien-cote-dazur-logo3.png"
  logoSize = 500
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "ElectricienCoteDazur"
  author = "ElectricienCoteDazur"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  #formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  

   [Languages.en.params.footer]
    # Footer Contact Info
    [Languages.en.params.footer.contactInfo]
      title   = "Contact Info"
      address = "France, Nice 06"
      phone   = "+33 07 53 81 78 02"
      email   = "ghenadye.ciobanu@gmail.com"
      # Footer Sitemap
      [Languages.en.params.footer.sitemap]
        title   = "Sitemap"
        [[Languages.en.params.footer.sitemap.link]]
          name = "About"
          url  = "/en/about"
        [[Languages.en.params.footer.sitemap.link]]
          name = "Services"
          url  = "/en/portfolio"
        [[Languages.en.params.footer.sitemap.link]]
          name = "Tarifs"
          url  = "/en/blog"
        [[Languages.en.params.footer.sitemap.link]]
          name = "Contact"
          url  = "/en/contact"  
        
      # Footer Social Media
      [Languages.en.params.footer.social]
        title   = "Social Media"
        [[Languages.en.params.footer.social.link]]
          name = "Youtube"
          url  = "#"
        
        [[Languages.en.params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/Electricien.Cote.dAzur"
        [[Languages.en.params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [Languages.en.params.footer.service]
        title       = "I speak:"
        description = " english <br>french<br>rusian<br>romanian"
    
    [Languages.fr.params.footer]
  # Footer Contact Info
      [Languages.fr.params.footer.contactInfo]
        title   = "Contact Info"
        address = "France, Nice 06"
        phone   = "+33 07 53 81 78 02"
        email   = "ghenadye.ciobanu@gmail.com"
         # Footer Sitemap
        [Languages.fr.params.footer.sitemap]
          title   = "Sitemap"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "À propos"
            url  = "/fr/about"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Services"
            url  = "/fr/portfolio"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Tarifs"
            url  = "/fr/blog"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Contact"
            url  = "/fr/contact"  
  
    # Footer Social Media
      [Languages.fr.params.footer.social]
        title   = "Social Media"
        [[Languages.fr.params.footer.social.link]]
          name = "Youtube"
          url  = "#"
        
        [[Languages.fr.params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/Electricien.Cote.dAzur"
        [[Languages.fr.params.footer.social.link]]
          name = "Instagram"
          url  = "#https://www.instagram.com/21centurykids_com/"
      # Footer Service
      [Languages.fr.params.footer.service]
        title       = "Je parle:"
        description = " français <br> anglais <br> russe <br> roumain"  

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
