baseURL       = "/"
languageCode  = "en-us"
title         = "ElectricienCoteDazur"
theme         = "roxo"
summarylength = 25
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "ElectricienCoteDazur"
weight = 1
languageName = "English"

  [[Languages.en.menu.main]]
     url     = "/portfolio"
     name    = "Books for Kids"
     weight  = 1
    
  [[Languages.en.menu.main]]
    url     = "/blog"
    name    = "Blog"
    weight  = 4
  [[Languages.en.menu.main]]
    url     = "/about"
    name    = "About"
    weight  = 5
  [[Languages.en.menu.main]]
    url     = "search/"
    name    = "Search"
    weight  = 6

  # Banner Section
    [Languages.en.params.banner]
    enable                = true
    background_image      = "images/backgrounds/ghenadie-ciobanu-electricien-cote-dazur2.jpg"
    heading               = "If you have a problem that requires the intervention of an electrician, you know who to call."
    tagline               = "My name is Ghenadie Ciobanu and I can't do everything! When I have a problem with my car, I go to the mechanic. If I feel bad, I go to the doctor. Each of us has experience in one or more fields, but we certainly cannot do them all. When it comes to electricity, this is the field in which I am an expert."
    primary_button        = "Blog"
    primary_button_url    = "/en/blog"
    secondary_button      = "Basics"
    secondary_button_url  = "portfolio"
  
  [Languages.en.params.blog]
    enable    = true
    title     = "Articles:"
    subtitle  = "Seeking to make the complex clear & practical." 
    more      = "VIEW MORE ARTICLES"
    viewarticle = "View Article" 
    
  [Languages.en.params.portfolio]
    enable    = true
    title     = "Books for Kids:"
    subtitle  = "Crafting experiences and working for sparkling in the children's eyes."
    more      = "VIEW MORE BOOKS"
    amazonbutton = "Buy on Amazon"
    viewbook = "View Book"
    

  

  [Languages.en.params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Read the Blog"
    primary_button_url  = "/en/blog"
    secondary_button    = "View Books for Kids"
    secondary_button_url = "/en/portfolio"



    
    
[Languages.fr]
title = "Electricien Cote D'azur"
weight = 2
languageName = "Français"

  [[Languages.fr.menu.main]]
    url     = "/fr/portfolio"
    name    = "Carti pentru Copii"
    weight  = 1
    
  [[Languages.fr.menu.main]]
    url     = "/fr/blog"
    name    = "Blog"
    weight  = 4  
  [[Languages.fr.menu.main]]
    url     = "/fr/about"
    name    = "Despre"
    weight  = 5
  [[Languages.fr.menu.main]]
    url     = "search/"
    name    = "Căutare"
    weight  = 6
  # Banner Section
    [Languages.fr.params.banner]
    enable                = true
    background_image      = "images/backgrounds/ghenadie-ciobanu-electricien-cote-dazur2.jpg"
    heading               = "Si vous avez un problème qui nécessite l'intervention d'un électricien, vous savez qui appeler. "
    tagline               = "Je m'appelle Ghenadie Ciobanu et je ne peux pas tout faire ! Quand j'ai un problème avec ma voiture, je vais chez le mécanicien. Si je me sens mal, je vais chez le médecin. Chacun de nous a de l'expérience dans un ou plusieurs domaines, mais nous ne pouvons certainement pas tous les faire.En matière d'électricité, c'est le domaine dans lequel je suis un expert."
    primary_button        = "Blog"
    primary_button_url    = "/fr/blog"
    secondary_button      = "Fundamente"
    secondary_button_url  = "portfolio"

  [Languages.fr.params.blog]
    enable    = true
    title     = "Articole:"
    subtitle  = "Complexitatea devine clară și practică."
    more      = "VEZI MAI MULTE ARTICOLE" 
    viewarticle = "Vezi Articolul"  

  [Languages.fr.params.portfolio]
    enable    = true
    title     = "Carti pentru copii:"
    subtitle  = "Cream experiențe și muncim pentru strălucirea din ochii copiilor."
    more      = "VEZI MAI MULTE CARTI"
    amazonbutton = "Cumpara pe Amazon"
    viewbook = "Vezi Cartea"

[Languages.fr.params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Creștem Împreună"
    primary_button      = "Merg la Blog"
    primary_button_url  = "/fr/blog"
    secondary_button    = "Cărți pentru Copii"
    secondary_button_url = "/fr/portfolio"
    

    
  
# # Site Menus
# [menu]
#   # Navbar Menus
#   [[menu.nav]]
#     name    = "Home"
#     url     = ""
#     weight  = 1
#   [[menu.nav]]
#     name    = "Despre"
#     url     = "about"
#     weight  = 2
#     [[menu.nav]]
#     name    = "FAQ"
#     url     = "portfolio"
#     weight  = 3
#   [[menu.nav]]
#     name    = "Blog"
#     url     = "blog"
#     weight  = 4
#   [[menu.nav]]
#     name    = "Contacte"
#     url     = "contact"
#     weight  = 5

# Site Params
[params]
  logo = "images/electricien-cote-dazur-logo3.png"
  logoSize = 500
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "21CenturyKids"
  author = "21CenturyKids"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  #formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  

   [Languages.en.params.footer]
    # Footer Contact Info
    [Languages.en.params.footer.contactInfo]
      title   = "Contact Info"
      address = "France, <br>Nice 06"
      phone   = ""
      email   = "info@21centurykids.com"
      # Footer Sitemap
      [Languages.en.params.footer.sitemap]
        title   = "Sitemap"
        [[Languages.en.params.footer.sitemap.link]]
          name = "About us"
          url  = "/en/about"
        [[Languages.en.params.footer.sitemap.link]]
          name = "Books for Kids"
          url  = "/en/portfolio"
        [[Languages.en.params.footer.sitemap.link]]
          name = "Blog"
          url  = "/en/blog"
        
      # Footer Social Media
      [Languages.en.params.footer.social]
        title   = "Social Media"
        [[Languages.en.params.footer.social.link]]
          name = "Youtube"
          url  = "#"
        
        [[Languages.en.params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[Languages.en.params.footer.social.link]]
          name = "Instagram"
          url  = "#https://www.instagram.com/21centurykids_com/"
      # Footer Service
      [Languages.en.params.footer.service]
        title       = "We help parents:"
        description = "to rise well balanced good kids<br>writing parenting advice content<br>and books for children"
    
    [Languages.fr.params.footer]
  # Footer Contact Info
      [Languages.fr.params.footer.contactInfo]
        title   = "Contact Info"
        address = "France, <br>Nice 06"
        phone   = ""
        email   = "info@21centurykids.com"
         # Footer Sitemap
        [Languages.fr.params.footer.sitemap]
          title   = "Harta Site"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Despre"
            url  = "/fr/about"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Carti pentru Copii"
            url  = "/fr/portfolio"
          [[Languages.fr.params.footer.sitemap.link]]
            name = "Blog"
            url  = "/fr/blog"
  
    # Footer Social Media
      [Languages.fr.params.footer.social]
        title   = "Social Media"
        [[Languages.fr.params.footer.social.link]]
          name = "Youtube"
          url  = "#"
        
        [[Languages.fr.params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[Languages.fr.params.footer.social.link]]
          name = "Instagram"
          url  = "#https://www.instagram.com/21centurykids_com/"
      # Footer Service
      [Languages.fr.params.footer.service]
        title       = "Ajutăm Părinții:"
        description = "să crească copii echilibrați<br>prin sfaturi practice de parenting<br>și cărți pentru copii"  

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
