baseURL       = "https://21centurykids.com/"
languageCode  = "en-us"
title         = "21CenturyKids"
theme         = "roxo"
summarylength = 25
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /ro/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "21CenturyKids"
weight = 1
languageName = "English"

  [[Languages.en.menu.main]]
     url     = "/portfolio"
     name    = "Books for Kids"
     weight  = 1
    
  [[Languages.en.menu.main]]
    url     = "/blog"
    name    = "Blog"
    weight  = 4
  [[Languages.en.menu.main]]
    url     = "/about"
    name    = "About"
    weight  = 5
  [[Languages.en.menu.main]]
    url     = "search/"
    name    = "Search"
    weight  = 6

  # Banner Section
    [Languages.en.params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "21st Century Kids are amazing, let's learn about them"
    tagline               = "With care for the future of our children..."
    primary_button        = "Blog"
    primary_button_url    = "/en/blog"
    secondary_button      = "Basics"
    secondary_button_url  = "portfolio"
  
  [Languages.en.params.blog]
    enable    = true
    title     = "Articles:"
    subtitle  = "Seeking to make the complex clear & practical." 
    more      = "VIEW MORE ARTICLES" 
  [Languages.en.params.portfolio]
    enable    = true
    title     = "Books for Kids:"
    subtitle  = "Crafting experiences and working for sparkling in the children's eyes."
    more      = "VIEW MORE BOOKS"

  

  [Languages.en.params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S GROW TOGETHER"
    primary_button      = "Read the Blog"
    primary_button_url  = "/en/blog"
    secondary_button    = "View Books for Kids"
    secondary_button_url = "/en/portfolio"



    
    
[Languages.ro]
title = "21 Century Kids"
weight = 2
languageName = "Română"

  [[Languages.ro.menu.main]]
    url     = "/ro/portfolio"
    name    = "Carti pentru Copii"
    weight  = 1
    
  [[Languages.ro.menu.main]]
    url     = "/ro/blog"
    name    = "Blog"
    weight  = 4  
  [[Languages.ro.menu.main]]
    url     = "/ro/about"
    name    = "Despre"
    weight  = 5
  [[Languages.ro.menu.main]]
    url     = "search/"
    name    = "Căutare"
    weight  = 6
  # Banner Section
    [Languages.ro.params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Copiii secolului 21 sunt minunați, să învățăm mai multe despre ei"
    tagline               = "Cu grijă pentru viitorul copiilor noștri..."
    primary_button        = "Blog"
    primary_button_url    = "/ro/blog"
    secondary_button      = "Fundamente"
    secondary_button_url  = "portfolio"

  [Languages.ro.params.blog]
    enable    = true
    title     = "Articole:"
    subtitle  = "Complexul devine clar & practic."
    more      = "VEZI MAI MULTE ARTICOLE"   
  [Languages.ro.params.portfolio]
    enable    = true
    title     = "Carti pentru copii:"
    subtitle  = "Cream experiențe și muncim pentru strălucirea din ochii copiilor."
    more      = "VEZI MAI MULTE CARTI"
    amazonbutton = "Cumpara pe Amazon"


    
    
  
# # Site Menus
# [menu]
#   # Navbar Menus
#   [[menu.nav]]
#     name    = "Home"
#     url     = ""
#     weight  = 1
#   [[menu.nav]]
#     name    = "Despre"
#     url     = "about"
#     weight  = 2
#     [[menu.nav]]
#     name    = "FAQ"
#     url     = "portfolio"
#     weight  = 3
#   [[menu.nav]]
#     name    = "Blog"
#     url     = "blog"
#     weight  = 4
#   [[menu.nav]]
#     name    = "Contacte"
#     url     = "contact"
#     weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  logoSize = 500
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "21CenturyKids"
  author = "21CenturyKids"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  #formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  

   [Language.en.params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      phone   = "409-896-1444"
      email   = "info@roxo.co"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
    
  [Languages.ro.params.footer]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
